name: brew

on:
  push:
    branches:
    - main

jobs:
  brew-install:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check
        run: |
          TAP_PATH=$(brew --repository)/Library/Taps/mlb-rs/homebrew-mlbt
          mkdir -p "$TAP_PATH"
          cp ./mlbt.rb "$TAP_PATH/mlbt.rb"
          brew install mlb-rs/mlbt/mlbt
